### ISSUE TITLE
How to databind with {{value}}

### ISSUE THREAD

**Issue by Yobikap** [willemdewit/java.properties.js#1]
Hi Willem,

I want to use your framework for i18n.

Can you show me a example how to databind {{value}} ?

Thanks.

**Comment by willemdewit** [comment]
The framework you use should take care of that. This library is only meant for reading a java-properties file as a javascript object. 
If you use ember, you can use [ember-cli-java-properties-to-object](https://github.com/willemdewit/ember-cli-java-properties-to-object) in combination with [ember-i18n](https://github.com/jamesarosen/ember-i18n) or [ember-cli-i18n](https://github.com/DavyJonesLocker/ember-cli-i18n)
