### ISSUE TITLE
missing replacement of escaped unicode characters e.g. \u00A9 to ©

### ISSUE THREAD

**Issue by justastefan** [willemdewit/java.properties.js#2]
Sorry for bugging you again. 

Java properties allow using unicode escaping:
myspecial.properties=\u00A9 or \u00FC or \u00DF

would turn into:
{ "myspecial": {"properties": "© or ü or ß"}}

Why this should work? the properties files are actually expected to be ISO 8859-1. which has a reduced charset. Thus there's no other way using UTF-8 characters then using \u<4 hex digits>.

There're a few solutions javascript decoding strategies that perform a similar encoding with \\u00A9 (double slash) which could be modified i guess.. http://stackoverflow.com/questions/7885096/how-do-i-decode-a-string-with-escaped-unicode

**Comment by willemdewit** [comment]
Javascript files can contain special characters. It is unclear to me what the issue is.

**Comment by justastefan** [comment]
Check the '# Unicode' section on https://en.wikipedia.org/wiki/.properties. java-properties usually are ascii files, which don't support letters like ó, ù, ... ok javascript does. so for performance reasons it would be awesome if the java.properties module would replace \u1234 in advance.

**Comment by willemdewit** [comment]
This is what the lib is doing right? Look at the [test](https://github.com/willemdewit/java.properties.js/blob/master/test/java.properties.js#L72).

**Comment by justastefan** [comment]
using the ember-cli-java-properties-to-object addon i ran into the issue that there these characters did remain unescaped.  i'll check and post an issue if that's somehow different over there.
